parameters:
  - name: configuration
    type: string
    default: "Release"
  - name: platform
    type: string
    default: ""
  - name: inputArtifactStem
    type: string
    default: ""

jobs:
- job: UITest${{ parameters.platform }}${{ parameters.configuration }}
  displayName: UI Test ${{ parameters.platform }} ${{ parameters.configuration }}
  variables:
    BuildPlatform: ${{ parameters.platform }}
    BuildConfiguration: ${{ parameters.configuration }}
    SrcPath: $(Build.Repository.LocalPath)
  pool:
    ${{ if eq(variables['System.CollectionId'], 'cb55739e-4afe-46a3-970f-1b49d8ee7564') }}:
      ${{ if ne(parameters.platform, 'ARM64') }}:
        name: SHINE-INT-Testing-x64
      ${{ else }}:
        name: SHINE-INT-Testing-arm64
    ${{ else }}:
      ${{ if ne(parameters.platform, 'ARM64') }}:
        name: SHINE-OSS-Testing-x64
      ${{ else }}:
        name: SHINE-OSS-Testing-arm64
  steps:
  - checkout: self
    submodules: false
    clean: true
    fetchDepth: 1
    fetchTags: false

  - download: current
    displayName: Download artifacts
    artifact: build-${{ parameters.platform }}-${{ parameters.configuration }}${{ parameters.inputArtifactStem }}

  - task: UseDotNet@2
    displayName: 'Install .NET 6 SDK'
    inputs:
      packageType: sdk
      version: '6.x'

  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: sdk
      version: '8.x'
      includePreviewVersions: true

  - task: VisualStudioTestPlatformInstaller@1
    displayName: Ensure VSTest Platform

  - pwsh: |-
      & '$(build.sourcesdirectory)\.pipelines\InstallWinAppDriver.ps1'
    displayName: Download and install WinAppDriver

  - ${{ if ne(parameters.platform, 'arm64') }}:
    - task: ScreenResolutionUtility@1
      inputs:
        displaySettings: 'optimal'

  - task: VSTest@2
    displayName: 'UI Tests'
    inputs:
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      testSelector: 'testAssemblies'
      searchFolder: '$(Pipeline.Workspace)\build-${{ parameters.platform }}-${{ parameters.configuration }}${{ parameters.inputArtifactStem }}'
      vstestLocationMethod: 'location' # otherwise fails to find vstest.console.exe
      vstestLocation: '$(Agent.ToolsDirectory)\VsTest\17.10.0\x64\tools\net462\Common7\IDE\Extensions\TestPlatform'
      uiTests: true
      rerunFailedTests: true
      # Look at all those naming schemes! Sheesh!
      testAssemblyVer2: |
        **\UnitTests-*.dll
        **\UnitTest-*.dll
        **\*UnitTests.dll
        **\*.UnitTest.dll
        **\*.Tests.dll
        **\*.Test.dll
        **\KeyboardManager*Test.dll
        **\UITests-FancyZones.dll
        **\UITests-FancyZonesEditor.dll
        !**\obj\**
        !**\ref\**
