parameters:
  - name: additionalBuildOptions
    type: string
    default: ''
  - name: buildConfigurations
    type: object
    default:
      - Release
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64
  - name: codeSign
    type: boolean
    default: false
  - name: artifactStem
    type: string
    default: ''
  - name: jobName
    type: string
    default: 'Build'
  - name: condition
    type: string
    default: ''
  - name: dependsOn
    type: object
    default: []
  - name: pool
    type: object
    default: []
  - name: beforeBuildSteps
    type: stepList
    default: []
  - name: variables
    type: object
    default: {}
  - name: publishArtifacts
    type: boolean
    default: true
  - name: signingIdentity
    type: object
    default: {}
  - name: enableCaching
    type: boolean
    default: false
  - name: runTests
    type: boolean
    default: true

  - name: versionNumber
    type: string
    default: '0.0.1'
  - name: csProjectsToPublish
    type: object
    default:
      - 'src/settings-ui/Settings.UI/PowerToys.Settings.csproj'
      - 'src/modules/launcher/PowerLauncher/PowerLauncher.csproj'
      - 'src/modules/previewpane/MonacoPreviewHandler/MonacoPreviewHandler.csproj'
      - 'src/modules/previewpane/MarkdownPreviewHandler/MarkdownPreviewHandler.csproj'
      - 'src/modules/previewpane/SvgPreviewHandler/SvgPreviewHandler.csproj'
      - 'src/modules/previewpane/SvgThumbnailProvider/SvgThumbnailProvider.csproj'
      - 'src/modules/FileLocksmith/FileLocksmithUI/FileLocksmithUI.csproj'

jobs:
- job: ${{ parameters.jobName }}
  ${{ if ne(length(parameters.pool), 0) }}:
    pool: ${{ parameters.pool }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  strategy:
    matrix:
      ${{ each config in parameters.buildConfigurations }}:
        ${{ each platform in parameters.buildPlatforms }}:
          ${{ config }}_${{ platform }}:
            BuildConfiguration: ${{ config }}
            BuildPlatform: ${{ platform }}
            ${{ if eq(platform, 'x86') }}:
              OutputBuildPlatform: Win32
            ${{ elseif eq(platform, 'Any CPU') }}:
              OutputBuildPlatform: AnyCPU
            ${{ else }}:
              OutputBuildPlatform: ${{ platform }}
  variables:
    # Azure DevOps abhors a vacuum
    # If these are blank, expansion will fail later on... which will result in direct substitution of the variable *names*
    # later on. We'll just... set them to a single space and if we need to, check IsNullOrWhiteSpace.
    # Yup.
    MSBuildCacheParameters: ' '
    JobOutputDirectory: $(Build.ArtifactStagingDirectory)
    LogOutputDirectory: $(Build.ArtifactStagingDirectory)\logs
    JobOutputArtifactName: build-$(BuildPlatform)-$(BuildConfiguration)${{ parameters.artifactStem }}
    NUGET_RESTORE_MSBUILD_ARGS: /p:Platform=$(BuildPlatform) # Required for nuget to work due to self contained
    NODE_OPTIONS: --max_old_space_size=16384
    ${{ if eq(parameters.runTests, true) }}:
      MSBuildMainBuildTargets: Build;Test
    ${{ else }}:
      MSBuildMainBuildTargets: Build
    ${{ insert }}: ${{ parameters.variables }}
  displayName: Build
  timeoutInMinutes: 240
  cancelTimeoutInMinutes: 1
  templateContext: # Required when this template is hosted in 1ES PT
    outputs:
    - output: pipelineArtifact
      artifactName: setup-$(BuildPlatform)
      targetPath: $(Build.ArtifactStagingDirectory)
  steps:
  - checkout: self
    clean: true
    submodules: true
    persistCredentials: True
    fetchTags: false
    fetchDepth: 1

  # Sets versions for all PowerToy created DLLs
  - pwsh: |-
      .pipelines/versionSetting.ps1 -versionNumber '${{ parameters.versionNumber }}' -DevEnvironment ''
    displayName: Set Versions.Prop

  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: sdk
      version: '8.x'

  - template: .\steps-restore-nuget.yml

  - pwsh: |-
      & "$(build.sourcesdirectory)\.pipelines\verifyAndSetLatestVCToolsVersion.ps1"
    displayName: Work around DD-1541167 (VCToolsVersion)

  - ${{ parameters.beforeBuildSteps }}

  - task: VSBuild@1
    ${{ if eq(parameters.runTests, true) }}:
      displayName: Build and Test PowerToys main project
    ${{ else }}:
      displayName: Build PowerToys main project
    inputs:
      solution: 'PowerToys.sln'
      vsVersion: 17.0
      msbuildArgs: >-
        -restore -graph
        /p:RestorePackagesConfig=true
        /p:CIBuild=true
        /bl:$(LogOutputDirectory)\build-0-main.binlog
        ${{ parameters.additionalBuildOptions }}
        $(MSBuildCacheParameters)
        /t:$(MSBuildMainBuildTargets)
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      msbuildArchitecture: x64
      maximumCpuCount: true
    ${{ if eq(parameters.enableCaching, true) }}:
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: CopyFiles@2
    displayName: Copy Symbols
    inputs:
      contents: |-
        **\*.pdb
        !**\vc143.pdb
        !**\*test*.pdb
      flattenFolders: True
      targetFolder: $(JobOutputDirectory)/symbols-$(BuildPlatform)/

  - pwsh: |-
      $p = "$(JobOutputDirectory)\"
      $userHash = ((Get-Item $p\PowerToysUserSetup*.exe | Get-FileHash).Hash);
      $machineHash = ((Get-Item $p\PowerToysSetup*.exe | Get-FileHash).Hash);
      $userPlat = "hash_user_$(BuildPlatform).txt";
      $machinePlat = "hash_machine_$(BuildPlatform).txt";
      $combinedUserPath = $p + $userPlat;
      $combinedMachinePath = $p + $machinePlat;
      
      echo $p

      echo $userPlat
      echo $userHash
      echo $combinedUserPath

      echo $machinePlat
      echo $machineHash
      echo $combinedMachinePath
      
      $userHash | out-file -filepath $combinedUserPath
      $machineHash | out-file -filepath $combinedMachinePath
    displayName: 'Calculating SHA256 hash'

  # Publishing the GPO files
  - pwsh: |-
      New-Item "$(JobOutputDirectory)/gpo" -Type Directory
      Copy-Item src\gpo\assets\* "$(JobOutputDirectory)/gpo" -Recurse
    displayName: Stage the GPO files

  # Running the tests may result in future jobs consuming artifacts out of this build
  - ${{ if eq(parameters.runTests, true) }}:
    - task: CopyFiles@2
      displayName: Stage entire build output
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '$(BuildPlatform)/$(BuildConfiguration)/**/*'
        targetFolder: '$(JobOutputDirectory)\$(BuildPlatform)\$(BuildConfiguration)'

  - ${{ if eq(parameters.publishArtifacts, true) }}:
    - publish: $(JobOutputDirectory)
      artifact: $(JobOutputArtifactName)
      displayName: Publish All Outputs
      condition: always()
