trigger:
  batch: true
  branches:
    include:
      - main
      - stable
  paths:
    exclude:
      - doc/*
      - temp/*
      - tools/*
      - '**.md'

pr:
  branches:
    include:
      - main
      - stable
  paths:
    exclude:
      - '**.md'
      - doc

variables:
  - name: runCodesignValidationInjectionBG
    value: false
  - name: EnablePipelineCache
    value: true

name: $(BuildDefinitionName)_$(date:yyMM).$(date:dd)$(rev:rrr)

parameters:
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64

stages:
  - ${{ each platform in parameters.buildPlatforms }}:
    - stage: Precheck
      jobs:
        - template: .pipelines/ci/templates/build-powertoys-precheck.yml

    - stage: Build_${{ platform }}
      displayName: Build ${{ platform }}
      dependsOn: [Precheck]
      jobs:
        - template: ./templates/job-build-project.yml
          parameters:
            condition: and(succeeded(),ne(stageDependencies.Precheck.Precheck.outputs['verifyBuildRequest.skipBuild'], 'Yes'))
            pool:
              ${{ if eq(variables['System.CollectionId'], 'cb55739e-4afe-46a3-970f-1b49d8ee7564') }}:
                name: SHINE-INT-L
              ${{ else }}:
                name: SHINE-OSS-L
            buildPlatforms: [ ${{ platform }} ]
            buildConfigurations: [Release]
