parameters:
  configuration: 'Release'
  platform: ''
  additionalBuildArguments: '/p:RestorePackagesConfig=true -m'

jobs:
- job: Build${{ parameters.platform }}${{ parameters.configuration }}
  displayName: Run UI tests ${{ parameters.platform }} ${{ parameters.configuration }}
  dependsOn: Precheck
  condition: and(succeeded(),ne(dependencies.Precheck.outputs['verifyBuildRequest.skipBuild'], 'Yes'))
  variables:
    BuildConfiguration: ${{ parameters.configuration }}
    BuildPlatform: ${{ parameters.platform }}
    NUGET_RESTORE_MSBUILD_ARGS: /p:Platform=${{ parameters.platform }} # Required for nuget to work due to self contained
    NODE_OPTIONS: --max_old_space_size=16384
  pool:
    demands: ImageOverride -equals SHINE-VS17-Latest
    ${{ if eq(variables['System.CollectionUri'], 'https://dev.azure.com/ms/') }}:
      name: SHINE-OSS-L
    ${{ if ne(variables['System.CollectionUri'], 'https://dev.azure.com/ms/') }}:
      name: SHINE-INT-L
  timeoutInMinutes: 120
  strategy:
    maxParallel: 10
  steps:
    - checkout: self
      fetchDepth: 1
      submodules: true
    - bash: |
        echo "##[debug]Debug text"