parameters:
  configuration: 'Release'
  platform: ''
  
jobs:
- job: UITest
  displayName: UI Test ${{ parameters.platform }} ${{ parameters.configuration }}
  dependsOn: Build${{ parameters.platform }}${{ parameters.configuration }}
  pool:
    ${{ if eq(variables['System.CollectionUri'], 'https://dev.azure.com/ms/') }}:
      name: SHINE-OSS-Testing-x64
    ${{ if ne(variables['System.CollectionUri'], 'https://dev.azure.com/ms/') }}:
      name: SHINE-INT-Testing-x64
  steps:
  - checkout: self

  - task: DownloadPipelineArtifact@2
    displayName: Download artifacts
    inputs:
      artifact: build-${{ parameters.platform }}-${{ parameters.configuration }}
      path: $(Build.ArtifactStagingDirectory)

  - task: UseDotNet@2
    displayName: 'Use .NET 6 SDK'
    inputs:
      packageType: sdk
      version: '6.x'

  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: sdk
      version: '8.x'
      includePreviewVersions: true

  - task: VisualStudioTestPlatformInstaller@1
    displayName: Ensure VSTest Platform

  - task: PowerShell@2
    displayName: 'Run UI Tests'
    inputs:
      targetType: filePath
      filePath: $(build.sourcesdirectory)\.pipelines\scripts\runUiTests.ps1
      arguments: >-
        -SearchFolder '$(Build.ArtifactStagingDirectory)\x64\**\UITests-FancyZonesEditor.dll'
        -VsConsolePath '$(Agent.ToolsDirectory)\VsTest\**'
        -MatchPattern '**\UITests-*.dll'
        -LogPath '$(Build.ArtifactStagingDirectory)\Logs'
        -ResultPath "$(Build.ArtifactStagingDirectory)\TestResults"
